# Generated by Django 4.2.7 on 2023-11-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
